### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ghost** [RaineBannister/node-raknet#1]
Hello.

I have a couple of questions.

What does the '1' do there @ https://github.com/RaineBannister/node-raknet/blob/master/ReliabilityLayer.js#L85

What does 'srrt' mean @ https://github.com/RaineBannister/node-raknet/blob/master/ReliabilityLayer.js#L78

What does 'rttVar' mean @ https://github.com/RaineBannister/node-raknet/blob/master/ReliabilityLayer.js#L79

What does 'rto' mean @ https://github.com/RaineBannister/node-raknet/blob/master/ReliabilityLayer.js#L87

**Comment by uwainium** [comment]
Haha, the 1 looks like a typo. The other variables there are part of the round trip algorithm that is very similar to the algorithm TCP utilitizes to determine if you need to resend a packet. I'll be pushing an update to this repo soon with unit tests, I'll add better variable names and remove that typo then.

**Comment by ghost** [comment]
I'm busy with a rewrite of your raknet server. It's pretty much more clear and slightly different. If you happen to have Discord, add me Zaseth#7550 so we can talk further in private.
